apiVersion: v1
name: plonegovbr
version: 1.0.0
appVersion: 1.0.0
description: Conjunto de ferramentas computacionais de código aberto, responsável por traduzir conteúdos digitais (texto, áudio e vídeo) para a Língua Brasileira de Sinais - LIBRAS
keywords:
- python
- http
- zeoserver
- zopeplone
- plone
home: https://gov.br
sources:
- https://github.com/plonegovbr/plone
maintainers:
- name: Ministério da Economia
  email: softwarepublico@planejamento.gov.br
engine: gotpl
