apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "plone.nustercache.fullname" . }}-configmap
  labels:
    app: {{ template "plone.zeoserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  nuster.cfg: |
    # Nuster Default-Config
        global
        debug
        nuster cache on data-size 200m
    frontend fe
        bind *:8080
        mode http
        default_backend be
        monitor-uri /health
    backend be
        mode http
        nuster cache on
        nuster rule only200
        http-response set-header X-Cache Hit
        server s1 {{ template "plone.instance.fullname" . }}:{{ .Values.plone.zeoserver.httpPort }}


