{{- if and .Values.plone.varnishcache.autoscaleEnabled .Values.plone.varnishcache.autoscaleMin .Values.plone.varnishcache.autoscaleMax }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "plone.varnishcache.fullname" . }}-autoscale
  labels:
    app: {{ template "plone.varnishcache.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  maxReplicas: {{ .Values.plone.varnishcache.autoscaleMax }}
  minReplicas: {{ .Values.plone.varnishcache.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ template "plone.varnishcache.fullname" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.plone.varnishcache.cpu.targetAverageUtilization }}
{{- end }}
